# Generated by Django 5.2.4 on 2026-03-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='categories/'),
        ),
    ]
